language: python

services:
  - couchdb

install:
- curl -fsSL https://deno.land/x/install/install.sh | sh -s -- v0.7.0
- export PATH="$HOME/.deno/bin:$PATH"

script:
- curl -X GET http://localhost:5984/
- deno run -A ./couch_test.ts
